"""
Worked examples for align_and_annotate's multishot priming.

Kept separate from alignment_pipeline.py so the pipeline module isn't
crowded with example data. Each entry's annotations are hand-written
against alignment_schema's shape (no 'word' field, 1-based indices,
'opposite_translation_index' rather than 'match') and against the
CURRENT tokenizer's actual output for its source_text/target_text --
see alignment_pipeline.few_shot_messages(), which re-tokenizes these
texts itself rather than trusting a hand-listed token count.
"""

FEW_SHOT_EXAMPLES = [
    {
        # First sentence of the Istanbul example from run_alignment_pipeline.py.
        "source_lang": "en", "target_lang": "es",
        "source_text": "Istanbul is the largest city in Turkey, a megacity, constituting the country's economic, cultural, and historical center.",
        "target_text": "Estambul es la ciudad más grande de Turquía, una megaciudad que constituye el centro económico, cultural e histórico del país.",
        "source_annotations": [
            {"meaning": ["Estambul"], "opposite_translation_index": [1]},
            {"meaning": ["es"], "opposite_translation_index": [2]},
            {"meaning": ["la"], "opposite_translation_index": [3]},
            {"meaning": ["más grande"], "opposite_translation_index": [5, 6],
             "footnote": "Spanish reorders noun-adjective: 'ciudad más grande' vs. 'largest city'."},
            {"meaning": ["ciudad"], "opposite_translation_index": [4]},
            {"meaning": ["de"], "opposite_translation_index": [7]},
            {"meaning": ["Turquía"], "opposite_translation_index": [8]},
            {"meaning": [], "opposite_translation_index": [9]},
            {"meaning": ["una"], "opposite_translation_index": [10]},
            {"meaning": ["megaciudad"], "opposite_translation_index": [11]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["que constituye"], "opposite_translation_index": [12, 13]},
            {"meaning": ["el"], "opposite_translation_index": [14]},
            {"meaning": ["país"], "opposite_translation_index": [22]},
            {"meaning": ["del"], "opposite_translation_index": [21]},
            {"meaning": ["del"], "opposite_translation_index": [21]},
            {"meaning": ["económico"], "opposite_translation_index": [16]},
            {"meaning": [], "opposite_translation_index": [17]},
            {"meaning": ["cultural"], "opposite_translation_index": [18]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["e"], "opposite_translation_index": [19]},
            {"meaning": ["histórico"], "opposite_translation_index": [20]},
            {"meaning": ["centro"], "opposite_translation_index": [15]},
            {"meaning": [], "opposite_translation_index": [23]},
        ],
        "target_annotations": [
            {"meaning": ["Istanbul"], "opposite_translation_index": [1]},
            {"meaning": ["is"], "opposite_translation_index": [2]},
            {"meaning": ["the"], "opposite_translation_index": [3]},
            {"meaning": ["city"], "opposite_translation_index": [5]},
            {"meaning": ["most"], "opposite_translation_index": [4]},
            {"meaning": ["large"], "opposite_translation_index": [4]},
            {"meaning": ["in"], "opposite_translation_index": [6]},
            {"meaning": ["Turkey"], "opposite_translation_index": [7]},
            {"meaning": [], "opposite_translation_index": [8]},
            {"meaning": ["a"], "opposite_translation_index": [9]},
            {"meaning": ["megacity"], "opposite_translation_index": [10]},
            {"meaning": ["which"], "opposite_translation_index": [12]},
            {"meaning": ["constitutes"], "opposite_translation_index": [12]},
            {"meaning": ["the"], "opposite_translation_index": [13]},
            {"meaning": ["center"], "opposite_translation_index": [23]},
            {"meaning": ["economic"], "opposite_translation_index": [17]},
            {"meaning": [], "opposite_translation_index": [18]},
            {"meaning": ["cultural"], "opposite_translation_index": [19]},
            {"meaning": ["and"], "opposite_translation_index": [21]},
            {"meaning": ["historical"], "opposite_translation_index": [22]},
            {"meaning": ["of the"], "opposite_translation_index": [15, 16]},
            {"meaning": ["country"], "opposite_translation_index": [14]},
            {"meaning": [], "opposite_translation_index": [24]},
        ],
    },
    {
        "source_lang": "es", "target_lang": "en",
        "source_text": "¡Socorro, me ha picado una víbora! ¿Cobra? No, gratis.",
        "target_text": "Help! I've been bitten by a viper! Does it cost money? No, it's free.",
        "source_annotations": [
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["Help"], "opposite_translation_index": [1]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["me", "myself", "I"], "opposite_translation_index": [3]},
            {"meaning": ["has", "have"], "opposite_translation_index": [4, 5, 6]},
            {"meaning": ["bitten", "stung"], "opposite_translation_index": [7]},
            {"meaning": ["a", "one"], "opposite_translation_index": [9]},
            {"meaning": ["viper", "snake"], "opposite_translation_index": [10]},
            {"meaning": [], "opposite_translation_index": [11]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["Cobra (the snake)", "Does it cost money?"], "opposite_translation_index": [12, 13, 14, 15],
             "footnote": "Pun: 'cobra' is both the snake and a form of 'cobrar' (to charge money), asked as a question."},
            {"meaning": [], "opposite_translation_index": [16]},
            {"meaning": ["No"], "opposite_translation_index": [17]},
            {"meaning": [], "opposite_translation_index": [18]},
            {"meaning": ["free", "gratis"], "opposite_translation_index": [20, 21, 22]},
            {"meaning": [], "opposite_translation_index": [23]},
        ],
        "target_annotations": [
            {"meaning": ["¡Socorro!", "¡Ayuda!"], "opposite_translation_index": [2]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["me"], "opposite_translation_index": [4]},
            {"meaning": ["ha"], "opposite_translation_index": [5]},
            {"meaning": ["ha"], "opposite_translation_index": [5]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["picado"], "opposite_translation_index": [6]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["una"], "opposite_translation_index": [7]},
            {"meaning": ["víbora"], "opposite_translation_index": [8]},
            {"meaning": [], "opposite_translation_index": [9]},
            {"meaning": ["cobra"], "opposite_translation_index": [11],
             "footnote": "Part of the pun rendering of 'Cobra?' as an English question."},
            {"meaning": ["lo"], "opposite_translation_index": [11]},
            {"meaning": ["cobra"], "opposite_translation_index": [11]},
            {"meaning": ["cobra", "dinero"], "opposite_translation_index": [11]},
            {"meaning": [], "opposite_translation_index": [12]},
            {"meaning": ["No"], "opposite_translation_index": [13]},
            {"meaning": [], "opposite_translation_index": [14]},
            {"meaning": [], "opposite_translation_index": []},
            {"meaning": ["gratis"], "opposite_translation_index": [15]},
            {"meaning": ["gratis"], "opposite_translation_index": [15]},
            {"meaning": ["gratis"], "opposite_translation_index": [15]},
            {"meaning": [], "opposite_translation_index": [16]},
        ],
    },
]
